"use client";

import { Poppins } from "next/font/google";
import { createContext } from "react";
import { useState } from "react";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });
export const ThemeContext = createContext();

export const metadata = {
  title: "Hoa Nguyen Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <html lang="en">
      <ThemeContext.Provider value={{ darkMode, setDarkMode }}>
        <body className={poppins.className + " " + (darkMode ? "scrollbar" : "scrollbar-light")}>{children}</body>
      </ThemeContext.Provider>
    </html>
  );
}
