"use client";

import Head from "next/head";
import { BsFillMoonStarsFill, BsCodeSlash, BsFillSunFill } from "react-icons/bs";
import { AiFillInstagram, AiFillGithub, AiFillLinkedin, AiFillCode } from "react-icons/ai";
import { SiAdobephotoshop, SiKotlin } from "react-icons/si";
import { CgNotes } from "react-icons/cg";
import { useState } from "react";
import { DiJava, DiPython, DiReact } from "react-icons/di";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const mainProperties = darkMode ? "dark" : "" + "pb-40";
  return (
    <div className={mainProperties}>
      <Head>
        <title>Hoa Nguyen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-60 dark:bg-gray-900 duration-300">
        <section className="min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className="text-xl dark:text-gray-300 dark:duration-300">wahwin</h1>

            <ul className="flex items-center">
              <li className="cursor-pointer text-xl">
                {darkMode ? (
                  <BsFillSunFill onClick={() => setDarkMode(!darkMode)} className="text-[#e3d184] duration-300" />
                ) : (
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" duration-300" />
                )}
              </li>
              <li>
                <a href="/Hoa_Nguyen_Resume.pdf" className="bg-gradient-to-r from-green-500 to-emerald-500 text-gray-100 px-4 py-2 rounded-md ml-8" target="_blank">
                  resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2  text-transparent bg-clip-text bg-gradient-to-r from-green-600 to-teal-600 font-medium md:text-6xl">hoa nguyen</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-300 dark:duration-300">life-time student and programmer.</h3>
            <p className="text-md py-5 leading-6 text-neutral-800 md:text-xl max-w-xl mx-auto dark:text-neutral-400 dark:duration-300">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
            </p>
          </div>

          <div className="text-7xl flex justify-center gap-16 py-3 text-teal-700">
            <a href="https://github.com/HooWahWin" target="_blank">
              <AiFillGithub />
            </a>
            <a href="https://www.instagram.com/hoanguyen_art/" target="_blank">
              <AiFillInstagram />
            </a>
            <a href="https://www.linkedin.com/in/hoa-nguyen-041434227/" target="_blank">
              <AiFillLinkedin />
            </a>
          </div>

          <img src="../IMG_4171.JPG" alt="profile pic" className="w-80 h-80 mx-auto my-20 rounded-full object-cover md:h-96 md:w-96" />
        </section>
        {/* second page */}

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-300 dark:duration-300">services i offer</h3>
            <p className="text-md py-5 leading-6 text-neutral-800 dark:text-neutral-400 dark:duration-300">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
            </p>
          </div>

          <div className="grid lg:grid-cols-3 gap-10 ">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-zinc-200 duration-300">
              <span className="flex justify-center">
                <CgNotes className="text-[8rem] text-green-600" />
              </span>
              <h3 className="text-lg font-medium pt-8 pb-2">classes currently taking</h3>
              <div className="grid grid-cols-1 gap-4">
                <div className=" py-3 rounded-lg shadow-md duration-300 bg-gray-200 hover:bg-gray-100 dark:bg-gray-300 dark:hover:bg-gray-200 cursor-pointer">csc 3102: advanced data structures</div>
                <div className=" py-3 rounded-lg shadow-md duration-300 bg-gray-200 hover:bg-gray-100 dark:bg-gray-300 dark:hover:bg-gray-200 cursor-pointer">csc 2259: advanced data structures</div>
                <div className=" py-3 rounded-lg shadow-md duration-300 bg-gray-200 hover:bg-gray-100 dark:bg-gray-300 dark:hover:bg-gray-200 cursor-pointer">
                  math 2090: differential equations & linear algebra
                </div>
                <div className=" py-3 rounded-lg shadow-md duration-300 bg-gray-200 hover:bg-gray-100 dark:bg-gray-300 dark:hover:bg-gray-200 cursor-pointer">biol 1002: general biology ii</div>
                <div className=" py-3 rounded-lg shadow-md duration-300 bg-gray-200 hover:bg-gray-100 dark:bg-gray-300 dark:hover:bg-gray-200 cursor-pointer">biol 1005: general biology lab</div>
              </div>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-zinc-200 duration-300">
              <span className="flex justify-center">
                <SiAdobephotoshop className="text-[8rem] text-sky-950" />
              </span>
              <h3 className="text-lg font-medium pt-8 pb-2">passion for art</h3>
              <p className="py-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
              <h4 className="py-4 text-green-500">tools i use to create digital art:</h4>
              <p className="text-neutral-800 py-1">digital drawing tablets</p>
              <p className="text-neutral-800 py-1">adobe photoshop</p>
              <p className="text-neutral-800 py-1">iPad and apple pencil</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-zinc-200 duration-300">
              <span className="flex justify-center">
                <BsCodeSlash className="text-[8rem] text-teal-600" />
              </span>
              <h3 className="text-lg font-medium pt-8 pb-2">technologies known</h3>
              <p className="py-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
